MyMVCTest04/Models/客戶聯絡人.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMVCTest04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 客戶聯絡人
    {
        public int Id { get; set; }
        public int 客戶Id { get; set; }
        public string 職稱 { get; set; }
        public string 姓名 { get; set; }
        public string Email { get; set; }
        public string 手機 { get; set; }
        public string 電話 { get; set; }
        public bool 是否已刪除 { get; set; }
    
        public virtual 客戶資料 客戶資料 { get; set; }
    }
}

MyMVCTest04/Controllers/客戶聯絡人Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyMVCTest04.Models;

namespace MyMVCTest04.Controllers
{
    public class 客戶聯絡人Controller : Controller
    {
        客戶聯絡人Repository repo = RepositoryHelper.Get客戶聯絡人Repository();

        public ActionResult ExcelFile()
        {
            return File(repo.GetExcelFile(), "application/vnd.ms-excel", "客戶聯絡人.xls");
        }

        // GET: 客戶聯絡人
        [CountExecutionTime()]
        public ActionResult Index(string position , string sortBy)
        {
            IQueryable<客戶聯絡人> data = null;
            if (!string.IsNullOrEmpty(position))
            {
                data = repo.All().Where(p => p.職稱.Contains(position));
                return View(data);
            }

            if (!string.IsNullOrEmpty(sortBy))
            {
                switch (sortBy)
                {
                    case "職稱":    
                            data = repo.All().OrderBy(p => p.職稱);
                        break;
                    case "姓名":
                            data = repo.All().OrderBy(p => p.姓名);
                        break;
                    case "Email":
                            data = repo.All().OrderBy(p => p.Email);
                        break;
                }
                return View(data);
            }


            return View(repo.All());
        }
        [HttpPost]
        public ActionResult Index(IList<客戶聯絡人> data)
        {
                foreach (var contact in data)
                {
                    var m_data = repo.Find(contact.Id);
                    m_data.電話 = contact.電話;
                    m_data.手機 = contact.手機;
                    m_data.職稱 = contact.職稱;                    
                }
                repo.UnitOfWork.Commit();
                return RedirectToAction("Index");
        }

        // GET: 客戶聯絡人/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
  
            客戶聯絡人 客戶聯絡人 = repo.Find(id);
            if (客戶聯絡人 == null)
            {
                return HttpNotFound();
            }
            return View(客戶聯絡人);
        }

        // GET: 客戶聯絡人/Create
        public ActionResult Create()
        {
            var repoCust = RepositoryHelper.Get客戶資料Repository(repo.UnitOfWork);
            ViewBag.客戶Id = new SelectList(repoCust.All() , "Id", "客戶名稱");
            return View();
        }

        // POST: 客戶聯絡人/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,客戶Id,職稱,姓名,Email,手機,電話,是否已刪除")] 客戶聯絡人 客戶聯絡人)
        {
            if (ModelState.IsValid)
            {
                repo.Add(客戶聯絡人);
                repo.UnitOfWork.Commit();
                return RedirectToAction("Index");
            }

            ViewBag.客戶Id = new SelectList(RepositoryHelper.Get客戶資料Repository(repo.UnitOfWork).All(), "Id", "客戶名稱", 客戶聯絡人.客戶Id);
            return View(客戶聯絡人);
        }

        // GET: 客戶聯絡人/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶聯絡人 客戶聯絡人 = repo.Find(id);
            if (客戶聯絡人 == null)
            {
                return HttpNotFound();
            }
            ViewBag.客戶Id = new SelectList(RepositoryHelper.Get客戶資料Repository(repo.UnitOfWork).All(), "Id", "客戶名稱", 客戶聯絡人.客戶Id);
            return View(客戶聯絡人);
        }

        // POST: 客戶聯絡人/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,客戶Id,職稱,姓名,Email,手機,電話,是否已刪除")] 客戶聯絡人 客戶聯絡人)
        {
            if (ModelState.IsValid)
            {
                var db = (客戶資料Entities)repo.UnitOfWork.Context;
                db.Entry(客戶聯絡人).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            ViewBag.客戶Id = new SelectList(RepositoryHelper.Get客戶資料Repository(repo.UnitOfWork).All(), "Id", "客戶名稱", 客戶聯絡人.客戶Id);
            return View(客戶聯絡人);
        }

        // GET: 客戶聯絡人/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            客戶聯絡人 客戶聯絡人 = repo.Find(id);
            if (客戶聯絡人 == null)
            {
                return HttpNotFound();
            }
            return View(客戶聯絡人);
        }

        // POST: 客戶聯絡人/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            客戶聯絡人 客戶聯絡人 = repo.Find(id);
            客戶聯絡人.是否已刪除 = true;
            repo.UnitOfWork.Commit();

            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

MyMVCTest04/Views/客戶聯絡人/Create.cshtml
@model MyMVCTest04.Models.客戶聯絡人

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶聯絡人</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id, "客戶Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.客戶Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.職稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.職稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.職稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.姓名, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.姓名, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.姓名, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.手機, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.手機, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.手機, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.電話, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.是否已刪除, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.是否已刪除)
                    @Html.ValidationMessageFor(model => model.是否已刪除, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyMVCTest04/Views/客戶聯絡人/Delete.cshtml
@model MyMVCTest04.Models.客戶聯絡人

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>客戶聯絡人</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.職稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.職稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.姓名)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.姓名)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.手機)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.手機)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.是否已刪除)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.是否已刪除)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MyMVCTest04/Views/客戶聯絡人/Details.cshtml
@model MyMVCTest04.Models.客戶聯絡人

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>客戶聯絡人</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.職稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.職稱)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.姓名)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.姓名)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.手機)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.手機)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.電話)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.電話)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.是否已刪除)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.是否已刪除)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.客戶資料.客戶名稱)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MyMVCTest04/Views/客戶聯絡人/Edit.cshtml
@model MyMVCTest04.Models.客戶聯絡人

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>客戶聯絡人</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.客戶Id, "客戶Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("客戶Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.客戶Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.職稱, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.職稱, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.職稱, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.姓名, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.姓名, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.姓名, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.手機, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.手機, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.手機, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.電話, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.電話, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.電話, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.是否已刪除, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.是否已刪除)
                    @Html.ValidationMessageFor(model => model.是否已刪除, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyMVCTest04/Views/客戶聯絡人/Index.cshtml
@model IEnumerable<MyMVCTest04.Models.客戶聯絡人>

@{
    ViewBag.Title = "Index";
}



<h2>搜尋職稱</h2>
@using (Html.BeginForm("Index","客戶聯絡人",FormMethod.Get))
{
    @Html.TextBox("position", null , new { onChange="this.form.submit();"})
}
<br />
執行時間: @ViewBag.execTime

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th> 
            @Html.ActionLink("客戶聯絡人", "Index", new { sortBy = "職稱" })
            @*@Html.DisplayNameFor(model => model.職稱)*@
        </th>
        <th>
            @Html.ActionLink("客戶聯絡人", "Index", new { sortBy = "姓名" })
            @*@Html.DisplayNameFor(model => model.姓名)*@
        </th>
        <th>
            @Html.ActionLink("客戶聯絡人", "Index", new { sortBy = "Email" })
            @*@Html.DisplayNameFor(model => model.Email)*@
        </th>
        <th>
            @Html.DisplayNameFor(model => model.手機)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.電話)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.是否已刪除)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.職稱)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.姓名)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.手機)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.電話)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.是否已刪除)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.客戶資料.客戶名稱)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}  
</table>
@using (@Html.BeginForm("ExcelFile", "客戶聯絡人"))
{
    <button class="btn btn-primary"> Excel </button>
}

MyMVCTest04/Views/客戶聯絡人/ListDetail.cshtml
@model IEnumerable<MyMVCTest04.Models.客戶聯絡人>

@{
    var data = Model.ToArray();
}
@using (Html.BeginForm("Index", "客戶聯絡人"))
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.職稱)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.姓名)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.手機)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.電話)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.客戶資料.客戶名稱)
            </th>
            <th></th>
        </tr>

        @for (int i = 0; i < data.Length; i++)
        {
            @Html.HiddenFor(modelItem => data[i].Id)
            <tr>
                <td>
                    @Html.EditorFor(modelItem => data[i].職稱)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => data[i].姓名)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => data[i].Email)
                </td>
                <td>
                    @Html.EditorFor(modelItem => data[i].手機)
                </td>
                <td>
                    @Html.EditorFor(modelItem => data[i].電話)
                </td>
                <th>
                    @Html.DisplayFor(model => data[i].客戶資料.客戶名稱)
                </th>
            </tr>
        }
    </table>

    <button class="btn btn-primary">批次更新</button>
}